import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend } from "next/font/google"; // 🔥 เพิ่ม Lexend ตรงนี้
import "./globals.css";
import Navbar from "@/components/navbar";

export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 🔥 เพิ่ม Config Lexend ตรงนี้
const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // 🔥 เพิ่ม lexend.variable เข้าไป และใส่ font-sans font-normal เพื่อให้เป็นตัวปกติทั้งเว็บ
        className={`${lexend.variable}  font-sans font-normal antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}